version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto_platform
    container_name: auto_platform
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
